language: c
dist: trusty
sudo: true

compiler:
  - gcc
  - clang

env:
  - NO_CUDA=1 NO_OPENMP=1
  - NO_CUDA=1
  - CUDA=6.5-14
  - CUDA=7.0-28
  - CUDA=7.5-18

before_install:
  - export LD_LIBRARY_PATH=/usr/local/clang-3.9.0/lib:${LD_LIBRARY_PATH}
  - if [[ -n ${CUDA} ]]; then travis_retry wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_${CUDA}_amd64.deb; fi
  - if [[ -n ${CUDA} ]]; then travis_retry sudo dpkg -i cuda-repo-ubuntu1404_${CUDA}_amd64.deb; fi
  - if [[ -n ${CUDA} ]]; then travis_retry sudo apt-get update -qq; fi
  - if [[ -n ${CUDA} ]]; then export CUDA_APT=${CUDA%-*}; fi
  - if [[ -n ${CUDA} ]]; then export CUDA_APT=${CUDA_APT/./-}; fi
  - if [[ -n ${CUDA} ]]; then travis_retry sudo apt-get install -y cuda-drivers cuda-core-${CUDA_APT} cuda-cudart-dev-${CUDA_APT}; fi
  - if [[ -n ${CUDA} ]]; then travis_retry sudo apt-get clean; fi
  - if [[ -n ${CUDA} ]]; then export CUDA_HOME=/usr/local/cuda-${CUDA%%-*}; fi
  - if [[ -n ${CUDA} ]]; then export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}; fi
  - if [[ -n ${CUDA} ]]; then export PATH=${CUDA_HOME}/bin:${PATH}; fi

script:
  - export
  - make CC=${CC} NO_OPENMP=${NO_OPENMP} NO_CUDA=${NO_CUDA}
  - ./nbody --bodies 8 --cycle-after 3 --iterations 1

notifications:
  pushover:
    api_key:
      secure: gsUWHn4C8WfV30HUnfUQFYSs9/prNNWI4WnuaHK7g33AnY+XqPM4h0sKfU9Wwlt0Uu13f9LNfIgk9nPnT9UxQoLzkG3uuVNWEQ3r62B76LzeBF9xprxMj/Ju9NP9SPqGnMAotKlAoNgQgrEf2B1hQV5RrLgsu8zdaatdDwLCoiU=
    users:
      secure: P09YDEei2k8LG9eRM/yW075iv9xNhxLpRLVzy8YP8kYhfDmhIFbc4eiYMCCKVxvUm654uWgmBfuQzGYTme+/YIs5D6itEwAu/It2d5TzwPkF743g90anz88bCUWZvfoj29Yd2OmtjJCpad6j6oq00nPqR5Oe/nXI7GfGS0V4p6U=
