language: cpp
sudo: required

arch: amd64

branches:
  except:
    - /^experimental\/.*$/

services:
  - docker

compiler:
  - gcc
  - clang

env:
  global:
    - CONTAINER_NAME=nbody-travis-docker-builder
  jobs:
    - IMAGE=ubuntu IMAGE_TAG=latest
    - IMAGE=ubuntu IMAGE_TAG=rolling
    - IMAGE=ubuntu IMAGE_TAG=devel
    - IMAGE=fedora IMAGE_TAG=latest
    - IMAGE=nvidia/cuda IMAGE_TAG=10.0-devel
    - IMAGE=nvidia/cuda IMAGE_TAG=10.1-devel

jobs:
  include:
    - arch: arm64
      env: IMAGE=ubuntu IMAGE_TAG=rolling
    #- arch: ppc64le
    #  env: IMAGE=ubuntu IMAGE_TAG=rolling

before_install:
  - docker run -d --name $CONTAINER_NAME -e LC_ALL="C" -e LANG="C" -v $(pwd):/travis -w /travis $IMAGE_PREFIX$IMAGE:$IMAGE_TAG tail -f /dev/null
  - docker ps

install:
  - docker exec -e CC=$CC -e CXX=$CXX -t $CONTAINER_NAME bash .travis/install-${IMAGE//\//-}.sh
  - docker exec -e CC=$CC -e CXX=$CXX -t $CONTAINER_NAME bash .travis/install-post.sh

script:
  - docker exec -e CC=$CC -e CXX=$CXX -t $CONTAINER_NAME bash .travis/script.sh

# vim: set ts=2 sts=2 sw=2 et:
